### ISSUE TITLE
add CSS to make code block background darker in Note

### ISSUE THREAD

**Issue by katydecorah** [mapbox/dr-ui#230]
We added this CSS in help to make the background of code blocks within Notes darker:
```css
.dr-ui--note pre {
  background: rgba(31, 51, 73, 0.05) !important;
}
```

Before
![](https://user-images.githubusercontent.com/10479155/72576078-77ccc080-3883-11ea-8546-a0a029f652f6.png)

After 
![](https://user-images.githubusercontent.com/2180540/72621297-fcb0ec00-390e-11ea-8df9-b74c948bdd4f.png)
