### ISSUE TITLE
Increase color contrast on `.color-gray code`

### ISSUE THREAD

**Issue by katydecorah** [mapbox/dr-ui#426]
As seen on: https://docs.mapbox.com/mapbox-gl-js/style-spec/terrain/

```css
.color-gray code {
  color: #56728f;
}
```
